server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  servlet:
    multipart:
      max-file-size: 10MB

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI5tSLGQLydzexjnWnJDFr
    keySecret: BudpMsQdeUEXgHz59FT1PQRePA8VJP
    bucketName: srb-file-20210908