server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    # 使用光连接
    type: com.zaxxer.hikari.HikariDataSource
    # mysql8.0版本驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 时区问题和字符集编码
    url: jdbc:mysql://120.77.151.32:3306/db_srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: password
  redis:
    host: 120.77.151.32
    port: 6379
    database: 0
    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mybatis-plus: #mybatis
  configuration:
    # log日志打印，sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/mellow/srb/core/mapper/xml/*.xml
